services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pass
      POSTGRES_DB: GroceryManager
    secrets:
      - source: postgres_pw
        target: pg_pass
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql
  rauthy:
    image: ghcr.io/sebadob/rauthy
    environment:
      LOCAL_TEST: true
      TLS_GENERATE_SELF_SIGNED: false
      LISTEN_SCHEME: http
      LISTEN_PORT_HTTP: 8081
      PUB_URL: localhost:8081
      RP_ORIGIN: http://localhost:8081
    ports:
      - "8081:8081"
  grocery-manager:
    image: ghcr.io/hartliks/grocerymanagement:master
    build:
      context: .
      target: run
    depends_on:
      - postgres
      - rauthy
    environment:
      SPRING_CONFIG_IMPORT: optional:configtree:/run/secrets/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER: "http://localhost:8081/auth/v1"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://rauthy:8081/auth/v1/oidc/certs"
    secrets:
      - source: postgres_pw
        target: spring.datasource.password
    ports:
      - "8080:8080"


volumes:
  pg-data:
    driver: "local"

secrets:
  postgres_pw:
    file: secrets/pg_pass