services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: GroceryManager
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql

volumes:
  pg-data:
    driver: "local"