quarkus:
  application:
    name: GroceryManager
  container-image:
    registry: ghcr.io
    group: hartliks
    name: grocerymanagement
    additional-tags: quarkus
    labels:
      "org.opencontainers.image.source": "https://github.com/HartlIKS/GroceryManagement"
    build: true
  datasource:
    db-kind: postgresql
    devservices:
      image-name: postgres:18-alpine
  keycloak:
    devservices:
      enabled: false
  liquibase:
    migrate-at-start: true
    change-log: db/changelog/db.changelog-master.yaml
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
    schema-management:
      strategy: validate
  quinoa:
    package-manager-install:
      ~: true
      node-version: 24.17.0