quarkus:
  application:
    name: GroceryManager
  http:
    static-dir:
      enabled: true
      endpoint: /
      path: ./frontend/dist/frontend/browser/
  oidc:
    auth-server-url: "http://localhost:8081"
    client-id: "GroceryManager"
  liquibase:
    migrate-at-start: true
    change-log: db/changelog/db.changelog-master.yaml
  hibernate-orm:
    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
    schema-management:
      strategy: validate