FROM eclipse-temurin:17-jre

ENV LANGUAGE='en_US:en'


# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --link target/quarkus-app/lib/ /deployments/lib/
COPY --link target/quarkus-app/*.jar /deployments/
COPY --link target/quarkus-app/app/ /deployments/app/
COPY --link target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080

WORKDIR /deployments
CMD ["java", "-Dquarkus.http.host=0.0.0.0", "-Djava.util.logging.manager=org.jboss.logmanager.LogManager", "-jar", "/deployments/quarkus-run.jar"]
