#
name: Create and publish a Docker image using Quarkus

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ["master"]
    paths:
      - .github/workflows/docker-image.yml
      - src/**
      - pom.xml
  workflow_dispatch:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      #
    steps:
      - uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: src/main/webui/package-lock.json
      - name: Build & publish
        run: mvn package -f pom.xml
        env:
          QUARKUS_CONTAINER_IMAGE_REGISTRY: ghcr.io
          QUARKUS_CONTAINER_IMAGE_USERNAME: ${{ github.actor }}
          QUARKUS_CONTAINER_IMAGE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          QUARKUS_CONTAINER_IMAGE_PUSH: true
          QUARKUS_CONTAINER_IMAGE_ADDITIONAL_TAGS: ${{ github.head_ref || github.ref_name }}
          QUARKUS_DOCKER_BUILDX_PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7"
          QUARKUS_DOCKER_CACHE_FROM: "type=registry,ref=ghcr.io/hartliks/grocerymanagement:buildcache"
          QUARKUS_DOCKER_ADDITIONAL_ARGS_0_: "--cache-to"
          QUARKUS_DOCKER_ADDITIONAL_ARGS_1_: "type=registry,ref=ghcr.io/hartliks/grocerymanagement:buildcache,mode=max,compression=zstd"
          QUARKUS_QUINOA_PACKAGE_MANAGER_INSTALL: false
          QUARKUS_QUINOA_FROZEN_LOCKFILE: true
