#
name: Create and publish a Docker image using Quarkus

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ["master"]
  workflow_dispatch:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      #
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: 24.x
          cache: 'npm'
          cache-dependency-path: src/main/webui/package-lock.json
      - name: Expose Github runtime
        uses: crazy-max/ghaction-github-runtime@v4
      - name: ghcr.io Login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & publish
        run: mvn package -f pom.xml
        env:
          QUARKUS_CONTAINER_IMAGE_REGISTRY: ghcr.io
          QUARKUS_CONTAINER_IMAGE_PUSH: true
          QUARKUS_CONTAINER_IMAGE_ADDITIONAL_TAGS: ${{ github.head_ref || github.ref_name }}
          QUARKUS_DOCKER_CACHE_FROM: type=gha
          QUARKUS_DOCKER_ADDITIONAL_ARGS: "--cache-to type=gha"
          QUARKUS_DOCKER_BUILDX_PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7"
          QUARKUS_QUINOA_PACKAGE_MANAGER_INSTALL: false
